### ISSUE TITLE
use ‘UpSample‘ in DCGAN, loss do not decline. use ‘ConvTranspose2d‘ in DAGAN，loss decline

### ISSUE THREAD

**Issue by 1210264601** [IdanAzuri/glico-learning-small-sample#1]
thank you  for the  work. 
 I meet a problem:  "use ‘UpSample‘  in DCGAN, loss do not decline.  use  ‘ConvTranspose2d‘ in DAGAN，loss   decline."

by the way, have you  re-upload the whole project?

**Comment by 1210264601** [comment]
![image](https://user-images.githubusercontent.com/11661034/88265974-f9a11900-cd00-11ea-9041-4a1c79590de8.png)

**Comment by iazuri** [comment]
@1210264601 , I'm not sure what is the issue.
And yes, I re-upload the whole project as a clean repo.

**Comment by IdanAzuri** [comment]
@1210264601 , I'm not sure what is the issue.
And yes, I re-upload the whole project as a clean repo.

**Comment by 1210264601** [comment]
as the picture I showed above， I add BN and RELUafter UPsample/conv2d.  Without these,  Loss in cglo cannot decline.

**Comment by IdanAzuri** [comment]
Please share your run params. Your reported issue doesn't make sense, as the loss is effectively computed by 2 factors: the classified and the reconstruction loss. So even if there is any problem with the classifier the reconstruction loss will decrease the loss anyway.
