### ISSUE TITLE
Module/File missing

### ISSUE THREAD

**Issue by shastripawas** [IdanAzuri/glico-learning-small-sample#4]
evaluation.py makes a reference to "cGAN.model" which is not present in this code.

**Comment by shastripawas** [comment]
@IdanAzuri

**Comment by IdanAzuri** [comment]
@shastripawas, thanks for reaching out. Indeed there is a missing module of the conditional GAN, however this is not evaluation script of GLICO. The relevant evaluation file can be found here: 

> glico_model/evaluation.py

**Comment by shastripawas** [comment]
Thank you for the clarification.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
